#!/bin/bash
#

echo corr01; ssh corr01.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr02; ssh corr02.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr03; ssh corr03.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr04; ssh eth0.corr04.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr05; ssh corr05.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr06; ssh corr06.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr07; ssh corr07.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr08; ssh corr08.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr09; ssh corr09.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr10; ssh corr10.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr11; ssh corr11.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr12; ssh corr12.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr13; ssh corr13.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr14; ssh corr14.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr15; ssh corr15.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr16; ssh corr16.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr17; ssh corr17.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr18; ssh corr18.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr19; ssh eth0.corr19.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr20; ssh corr20.sas.pvt "source ~/.bashrc; nvidia-smi"
echo corr21; ssh eth0.corr21.sas.pvt "source ~/.bashrc; nvidia-smi"
